spring.application.name=SmartFit
spring.datasource.url=jdbc:mysql://localhost:3306/SmartFitdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server configuration :
server.port=9090